import type { Metadata } from "next";
import "./globals.css";
import LogoutButton from "../components/LogoutButton";
import { cookies } from 'next/headers';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const auth = (await cookies()).get('auth')?.value === 'true';

  return (
    <html lang="en">
      <body>
        {auth && <LogoutButton />}
        {children}
      </body>
    </html>
  );
}
